import type { RegimeConfig, TaxRegime } from '../interfaces';

const INDIAN_STATES: Record<string, string> = {
  '01': 'Jammu & Kashmir',
  '02': 'Himachal Pradesh',
  '03': 'Punjab',
  '04': 'Chandigarh',
  '05': 'Uttarakhand',
  '06': 'Haryana',
  '07': 'Delhi',
  '08': 'Rajasthan',
  '09': 'Uttar Pradesh',
  '10': 'Bihar',
  '11': 'Sikkim',
  '12': 'Arunachal Pradesh',
  '13': 'Nagaland',
  '14': 'Manipur',
  '15': 'Mizoram',
  '16': 'Tripura',
  '17': 'Meghalaya',
  '18': 'Assam',
  '19': 'West Bengal',
  '20': 'Jharkhand',
  '21': 'Odisha',
  '22': 'Chhattisgarh',
  '23': 'Madhya Pradesh',
  '24': 'Gujarat',
  '26': 'Dadra & Nagar Haveli and Daman & Diu',
  '27': 'Maharashtra',
  '28': 'Andhra Pradesh (Old)',
  '29': 'Karnataka',
  '30': 'Goa',
  '31': 'Lakshadweep',
  '32': 'Kerala',
  '33': 'Tamil Nadu',
  '34': 'Puducherry',
  '35': 'Andaman & Nicobar Islands',
  '36': 'Telangana',
  '37': 'Andhra Pradesh',
  '38': 'Ladakh',
};

const EU_COUNTRIES: Record<string, string> = {
  AT: 'Austria',
  BE: 'Belgium',
  BG: 'Bulgaria',
  HR: 'Croatia',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  EE: 'Estonia',
  FI: 'Finland',
  FR: 'France',
  DE: 'Germany',
  GR: 'Greece',
  HU: 'Hungary',
  IE: 'Ireland',
  IT: 'Italy',
  LV: 'Latvia',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MT: 'Malta',
  NL: 'Netherlands',
  PL: 'Poland',
  PT: 'Portugal',
  RO: 'Romania',
  SK: 'Slovakia',
  SI: 'Slovenia',
  ES: 'Spain',
  SE: 'Sweden',
};

const US_STATES: Record<string, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};

export const REGIME_CONFIGS: Record<TaxRegime, RegimeConfig> = {
  gst_india: {
    name: 'India GST',
    registrationLabel: 'GSTIN',
    registrationPattern:
      '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$',
    componentNames: ['CGST', 'SGST', 'IGST'],
    standardRates: [0, 5, 12, 18, 28],
    taxCodeLabel: 'HSN/SAC Code',
    taxCodePattern: '^[0-9]{4,8}$',
    regions: INDIAN_STATES,
    categories: [
      { id: 'exempt', label: 'Exempt (0%)', rate: 0 },
      { id: 'food_5', label: 'Food - Non-AC (5%)', rate: 5 },
      { id: 'standard_12', label: 'Standard (12%)', rate: 12 },
      { id: 'food_18', label: 'Food - AC/Takeaway (18%)', rate: 18 },
      { id: 'luxury_28', label: 'Luxury/Alcohol (28%)', rate: 28 },
      { id: 'custom', label: 'Custom Rate', rate: -1 },
    ],
  },

  vat_eu: {
    name: 'EU VAT',
    registrationLabel: 'VAT Number',
    registrationPattern: '^[A-Z]{2}[0-9A-Z+*.]{2,12}$',
    componentNames: ['VAT'],
    standardRates: [0, 4, 5, 9, 10, 13, 19, 20, 21, 23, 25, 27],
    taxCodeLabel: 'CN Code',
    taxCodePattern: '^[0-9]{4,10}$',
    regions: EU_COUNTRIES,
    categories: [
      { id: 'exempt', label: 'Exempt (0%)', rate: 0 },
      { id: 'super_reduced', label: 'Super Reduced (4%)', rate: 4 },
      { id: 'reduced', label: 'Reduced (10%)', rate: 10 },
      { id: 'standard', label: 'Standard (21%)', rate: 21 },
      { id: 'custom', label: 'Custom Rate', rate: -1 },
    ],
  },

  vat_uk: {
    name: 'UK VAT',
    registrationLabel: 'VAT Number',
    registrationPattern:
      '^GB[0-9]{9}$|^GB[0-9]{12}$|^GBGD[0-9]{3}$|^GBHA[0-9]{3}$',
    componentNames: ['VAT'],
    standardRates: [0, 5, 20],
    taxCodeLabel: 'Commodity Code',
    taxCodePattern: '^[0-9]{4,10}$',
    regions: { GB: 'United Kingdom' },
    categories: [
      { id: 'zero_rated', label: 'Zero Rated (0%)', rate: 0 },
      { id: 'reduced', label: 'Reduced (5%)', rate: 5 },
      { id: 'standard', label: 'Standard (20%)', rate: 20 },
      { id: 'custom', label: 'Custom Rate', rate: -1 },
    ],
  },

  sales_tax_us: {
    name: 'US Sales Tax',
    registrationLabel: 'Tax ID (EIN)',
    registrationPattern: '^[0-9]{2}-[0-9]{7}$',
    componentNames: ['State Tax', 'County Tax', 'City Tax'],
    standardRates: [0, 4, 5, 6, 6.25, 6.5, 7, 7.25, 8, 8.25, 9, 10],
    taxCodeLabel: 'Tax Code',
    regions: US_STATES,
    categories: [
      { id: 'exempt', label: 'Exempt (0%)', rate: 0 },
      { id: 'food_reduced', label: 'Food (Reduced)', rate: 2 },
      { id: 'standard', label: 'Standard Rate', rate: -1 },
      { id: 'custom', label: 'Custom Rate', rate: -1 },
    ],
  },

  custom: {
    name: 'Custom Tax',
    registrationLabel: 'Tax ID',
    registrationPattern: '^.{2,50}$',
    componentNames: ['Tax'],
    standardRates: [0, 5, 10, 15, 18, 20, 25],
    taxCodeLabel: 'Tax Code',
    regions: {},
    categories: [
      { id: 'exempt', label: 'Exempt (0%)', rate: 0 },
      { id: 'reduced', label: 'Reduced Rate', rate: 5 },
      { id: 'standard', label: 'Standard Rate', rate: 10 },
      { id: 'custom', label: 'Custom Rate', rate: -1 },
    ],
  },
};

export function getRegimeConfig(regime: TaxRegime): RegimeConfig {
  return REGIME_CONFIGS[regime];
}
